#!/bin/bash

network_name="retrowave"
image_name="retrowave-fs"
container_name="${image_name}-1"

docker rm -f ${container_name}

docker run \
  -d \
  --restart unless-stopped \
  --network ${network_name} \
  --dns-opt 'ndots:1' \
  -v ~/Music/:/var/data/retrowave-fs/upload/ \
  --name ${container_name} \
  ${image_name}
